#ifndef SMALLRL_CHAOS_SPELLS_H
#define SMALLRL_CHAOS_SPELLS_H

#include "chaos_internal.h"

spell_t chaos_spell_disbelieve = {
    .order = spell_order_neutral,
    .name = "Disbelieve",
    .range = 20,
    .type = spell_type_projectile,
    .is_stoppable = false,
    .subtype = (int)spell_projectile_type_disbelieve,
    .difficulty = -1,
    .is_free = false,
};

spell_t chaos_spells[34] = {
    {
        .order = spell_order_law,
        .name = "Bat",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_bat,
        .difficulty = 1,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Bear",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_bear,
        .difficulty = 3,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Lion",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_lion,
        .difficulty = 3,
        .is_free = false
    },
    {
        .order = spell_order_law,
        .name = "Elf",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_elf,
        .difficulty = 3,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Eagle",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_eagle,
        .difficulty = 3,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Ghost",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_ghost,
        .difficulty = 4,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Zombie",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_zombie,
        .difficulty = 0,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Golden Dragon",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_dragon_gold,
        .difficulty = 7,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Centaur",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_centaur,
        .difficulty = 2,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Green Dragon",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_dragon_green,
        .difficulty = 7,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Hydra",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_hydra,
        .difficulty = 4,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Skeleton",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_skeleton,
        .difficulty = 2,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Ogre",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_ogre,
        .difficulty = 2,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Goblin",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_goblin,
        .difficulty = 0,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "King cobra",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_king_cobra,
        .difficulty = 0,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Wraith",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_wraith,
        .difficulty = 3,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Harpy",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_harpy,
        .difficulty = 2,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Giant rat",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_giant_rat,
        .difficulty = 0,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Unicorn",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_unicorn,
        .difficulty = 3,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Orc",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_orc,
        .difficulty = 0,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Giant",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_giant,
        .difficulty = 5,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Gryphon",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_gryphon,
        .difficulty = 3,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Pegasus",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_pegasus,
        .difficulty = 2,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Gorilla",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_gorilla,
        .difficulty = 2,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Elf",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_elf,
        .difficulty = 2,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Red Dragon",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_dragon_red,
        .difficulty = 8,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Manticore",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_manticore,
        .difficulty = 5,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Dire Wolf",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_dire_wolf,
        .difficulty = 0,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Spectre",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_spectre,
        .difficulty = 3,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Lion",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_lion,
        .difficulty = 1,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Faun",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_faun,
        .difficulty = 1,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Horse",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_horse,
        .difficulty = 0,
        .is_free = false,
    },
    {
        .order = spell_order_law,
        .name = "Eagle",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_eagle,
        .difficulty = 1,
        .is_free = false,
    },
    {
        .order = spell_order_chaos,
        .name = "Vampire",
        .range = 1,
        .type = spell_type_conjure,
        .is_stoppable = true,
        .subtype = (int)spell_conjure_type_vampire,
        .difficulty = 6,
        .is_free = false,
    }
};

#endif
